version: '3'
services:

  dev_database:
    container_name: mysql_container
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mount/dev/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --sql_mode=""
    networks:
      #      - meatmi_network_bridge
      - network

  adminDB:
    container_name: adminDB_container
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - dev_database
    ports:
      - 82:80
    links:
      - dev_database:dev_db
    networks:
      #      - meatmi_network_bridge
      - network

  spring-app:
    image: ilyeshamdi/spring-app:latest
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8082:8082"
